[package]
name = "tracing-oslog"
version = "0.2.0"
authors = ["Dummy"]
edition = "2021"

[dependencies]
tracing-core = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry"] }
cfg-if = "1.0"
once_cell = "1.19"
parking_lot = "0.12"
